[package]
name = "tdx-quote"
version = "0.1.0"
edition = "2021"

[dependencies]
nom = { version = "7.1.3", default-features = false }
p256 = { version = "0.13.2", default-features = false, features = ["ecdsa"]}
